Display ids as decimal, not hexa
shaj13/raft pull request #19
Opened 2023-06-16 09:06 UTC by rakoo

Hey there, thanks a lot for your project it's a great help !

I noticed in logs that the ids are funky, sometimes referring to "a" even though it's supposed to be a `uint64`. This is because the format was wrong. Here's a fix

2023-06-26 05:40 UTC, Tochemey requested changes
I think your pr is not supposed to change package path otherwise you will break existing code. I suggest you make your fix without changing the packages paths. Thank you

2023-06-26 05:40 UTC, Tochemey commented on Makefile
> +	GOFLAGS=-mod=vendor go test github.com/rakoo/raft/rafttest -race
Why are you making this change?

2023-06-26 05:40 UTC, Tochemey commented on controller.go
> +	"github.com/rakoo/raft/internal/membership"
Why this change?

2023-06-26 05:41 UTC, Tochemey requested changes

2023-06-26 05:41 UTC, Tochemey commented on internal/membership/pool_test.go
> +	"github.com/rakoo/raft/internal/raftpb"
Please revert these changes otherwise I am afraid this PR will not be merged.

2023-06-28 15:26 UTC, rakoo commented
Oops, sorry, I made a mistake pushing the path change. Reopened at !20

2023-06-28 15:26 UTC, closed without merging